src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /*
    * @var string
    */
    public function __toString() {
        return "test";
    }


}

templates/base.html copy.twig
<!DOCTYPE html>
<html>
<head>
	{% block script %}
		<script src={{ asset('assets/js/jquery.js') }}></script>
		<script src={{ asset('assets/js/bootstrap.min.js') }}></script>
		<script src={{ asset('assets/js/jquery.dataTables.js') }}></script>
		<script src={{ asset('assets/js/dataTables.bootstrap4.min.js') }}></script>
	{% endblock %}
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	{% block stylesheets %}

		<link rel="stylesheet" href={{ asset("assets/css/bootstrap.min.css") }}>
		<link rel="stylesheet" href={{ asset("assets/css/dataTables.bootstrap4.min.css") }}>
{#		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">#}


{#		<link rel="stylesheet" type="text/css" href="{{ asset('assets/main.css' ) }}">#}
	{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-primary mb-3 border-bottom border-secondary">
	<div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
		<a class="navbar-brand" href="{{ path('dossier_pret_redirect') }}">Empruntica |</a>
		<ul class="navbar-nav mr-auto text-center">
			{% if is_granted('ROLE_SECRETARIAT_MIAGE') or is_granted('ROLE_SECRETARIAT_ISRI') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_dashboard_administration', {"page": "etudiant"}) }}">Administration</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_INFORMATIQUE') or is_granted('ROLE_ADMIN') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_dashboard', {"page": "inventaire"}) }}">Informatique</a>
				</li>
			{% endif %}

			{% if is_granted('ROLE_SECRETARIAT_MIAGE') or is_granted('ROLE_SECRETARIAT_ISRI') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_secretariat') }}">Secrétariat</a>
				</li>

			{% endif %}
			{% if is_granted('ROLE_RESPONSABLE') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_responsable') }}">Responsable</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_ADMIN') or is_granted('ROLE_RESPONSABLE') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('duree_pret_index') }}">Durée prêt</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_terminer') }}">Archive</a>
				</li>
			{% endif %}

			{% if is_granted('ROLE_INFORMATIQUE') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_affectation') }}">Affectation équipement</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_attente_etudiant') }}">Attente étudiant</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_retour') }}">Retour étudiant</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_ETUDIANT') or is_granted('ROLE_PROFESSEUR') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_mon_dossier') }}">Mon compte</a>
				</li>
				<li>
					<a class="nav-link" href="{{ path('dossier_pret_new') }}">Faire une demande</a>

				</li>

			{% endif %}
		</ul>
	</div>

	<div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
		<ul class="navbar-nav ml-auto">


			{% if (app.user) %}
				<li class="nav-item">
					<p>{{ app.user.username ?? 'anonyme' }}</p>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ path('app_logout') }}">Déconnexion</a>
				</li>
			{% else %}
				<li class="nav-item">
					<a href="{{ path('app_login') }}" class="btn btn-secondary">Espace administration</a>
				</li>

			{% endif %}
		</ul>
	</div>
</nav>
<div class="container-fluid">
{% block body %}{% endblock %}
</div>
{% block javascripts %}
{#	<script src={{ asset('assets/js/jquery.js') }}></script>#}
{#	<script src={{ asset('assets/js/popper.min.js') }}></script>#}
	{#<script src={{ asset('assets/js/bootstrap.min.js') }}></script>
	<script src={{ asset('assets/js/jquery.dataTables.js') }}></script>
	<script src={{ asset('assets/js/dataTables.bootstrap4.min.js') }}></script>#}
{% endblock %}
</body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
	{% block script %}
		<script src={{ asset('assets/js/jquery.js') }}></script>
		<script src={{ asset('assets/js/bootstrap.min.js') }}></script>
		<script src={{ asset('assets/js/jquery.dataTables.js') }}></script>
		<script src={{ asset('assets/js/dataTables.bootstrap4.min.js') }}></script>
	{% endblock %}
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	{% block stylesheets %}

		<link rel="stylesheet" href={{ asset("assets/css/bootstrap.min.css") }}>
		<link rel="stylesheet" href={{ asset("assets/css/dataTables.bootstrap4.min.css") }}>
{#		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">#}


{#		<link rel="stylesheet" type="text/css" href="{{ asset('assets/main.css' ) }}">#}
	{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-primary mb-3 border-bottom border-secondary">
	<div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
		<a class="navbar-brand" href="{{ path('dossier_pret_redirect') }}">Empruntica |</a>
		<ul class="navbar-nav mr-auto text-center">
			{% if is_granted('ROLE_SECRETARIAT_MIAGE') or is_granted('ROLE_SECRETARIAT_ISRI') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_dashboard_administration', {"page": "etudiant"}) }}">Administration</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_INFORMATIQUE') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_dashboard', {"page": "inventaire"}) }}">Matériel</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_SECRETARIAT_MIAGE')
				or is_granted('ROLE_SECRETARIAT_ISRI')
				or is_granted('ROLE_RESPONSABLE_MIAGE')
				or is_granted('ROLE_RESPONSABLE_ISRI')
			%}
				<li>
					<a target="_blank" class="nav-link" href="{{ asset('assets/file/scan_fiche_pret.pdf') }}">Imprimer une fiche de prêt</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_SECRETARIAT_MIAGE') or is_granted('ROLE_SECRETARIAT_ISRI') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_secretariat') }}">Scolarité</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_RESPONSABLE_MIAGE') or is_granted('ROLE_RESPONSABLE_ISRI') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_responsable') }}">Responsable</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_ADMIN') or (is_granted('ROLE_RESPONSABLE_MIAGE') or is_granted('ROLE_RESPONSABLE_ISRI')) %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('duree_pret_index') }}">Durée prêt</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_terminer') }}">Archive</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_INFORMATIQUE') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_affectation') }}">Affectation équipement</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_attente_etudiant') }}">Attente étudiant</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_retour') }}">Retour étudiant</a>
				</li>
				<li>
					<a class="nav-link" href="{{ path('professeur_form') }}">Ajout membre UPJV</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_ETUDIANT') or is_granted('ROLE_PROFESSEUR') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('dossier_pret_mon_dossier') }}">Mon compte</a>
				</li>
				<li>
					<a class="nav-link" href="{{ path('dossier_pret_new') }}">Faire une demande</a>
				</li>
			{% endif %}
			{% if is_granted('ROLE_INFORMATIQUE') or is_granted('ROLE_SECRETARIAT_MIAGE') or is_granted('ROLE_SECRETARIAT_ISRI') %}
				<li class="nav-item">
					<a class="nav-link" href="{{ path('etudiant_form') }}">Faire une demande pour un étudiant</a>
				</li>
			{% endif %}
		</ul>
	</div>

	<div class="navbar-collapse collapse w-50 order-3 dual-collapse2">
		<ul class="navbar-nav ml-auto">


			{% if (app.user) %}
				<li class="nav-item">
					<p>{{ app.user.username ?? 'anonyme' }}</p>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ path('app_logout') }}">Déconnexion</a>
				</li>
			{% else %}
				<li class="nav-item">
					<a href="{{ path('app_login') }}" class="btn btn-secondary">Espace administration</a>
				</li>

			{% endif %}
		</ul>
	</div>
</nav>
<div class="container-fluid">
{% block body %}{% endblock %}
</div>
</body>
</html>